version: '3.7'

services:
  db:
    image: postgres:10
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  web:
    build: .
    ports:
      - '3000:3000'
      - '8025:8025'
      - '1025:1025'
    links:
      - db

volumes:
  pg_data: {}